### ISSUE TITLE
Location of the Java source code

### ISSUE THREAD

**Issue by hastebrot** [kieler/klayjs#16]
For those who wonder where to find the Java source.

On the Git repository server is the [`KIELER` project](http://git.rtsys.informatik.uni-kiel.de/projects/KIELER). It contains the `pragmatics` subproject, where you can find the [`klayjs` source branch](http://git.rtsys.informatik.uni-kiel.de/projects/KIELER/repos/pragmatics/browse?at=refs%2Fheads%2Fklayjs). Cloning the whole repository transfers currently circa 210 MiB.

For instance `KlayLayered.java` &mdash; a main class that contains the KLay Layered layout algorithm &mdash; is at the location 

> plugins/de.cau.cs.kieler.klay.layered/src/de/cau/cs/kieler/klay/layered/KlayLayered.java

Effectively:

```
$ git clone http://git.rtsys.informatik.uni-kiel.de/scm/kieler/pragmatics.git
$ cd pragmatics/
$ git checkout origin/klayjs
```

**Comment by jbeard4** [comment]
Are GWT build instructions available? Thank you.

**Comment by uruuru** [comment]
There is an [ant script](http://git.rtsys.informatik.uni-kiel.de/projects/KIELER/repos/pragmatics/browse/build/de.cau.cs.kieler.klayjs/build.xml?at=klayjs) which currently is called from a [gradle script](http://git.rtsys.informatik.uni-kiel.de/projects/KIELER/repos/pragmatics/browse/build/de.cau.cs.kieler.klayjs/build.gradle?at=klayjs) that is used to execute GWT. It is located in the `build/de.cau.cs.kieler.klayjs` plugin, you are looking for the `plainjslinker` target 

With the ongoing move of the Java code to the [ELK Project](https://github.com/eclipse/elk) the build scripts will eventually move there as well and hopefully be refactored to be a single gradle script. 

Usually we compile nightly builds based on the Java master. However, due to the shift to ELK these are currently not working.

**Comment by hastebrot** [comment]
@uruuru How deep is the coupling with Eclipse in ELK? Are there a lot of Eclipse libraries needed at runtime?

**Comment by uruuru** [comment]
@hastebrot if you are referring to the planned js version of ELK, it'll look just the same as klay.js. In other words, no eclipse dependencies and a single .js file.

**Comment by uruuru** [comment]
Closing, since elkjs is available now.
