### ISSUE TITLE
collapse parent

### ISSUE THREAD

**Issue by forresto** [kieler/klayjs#25]
Is there a property to collapse parent/group nodes? Or is that generally done manually to the graph, before handing to layout?

**Comment by uruuru** [comment]
Usually this must be done by the surrounding framework. The layout algorithm is not allowed to change the structure of the graph. 

You should, however, be able specify the fixed layouter for a certain hierarchical node (`de.cau.cs.kieler.algorithm: "de.cau.cs.kieler.fixed"`) in order to exclude the node's children from the layout process.
